### ISSUE TITLE
sync from intervals.icu to TP fails due to "yoga" workout

### ISSUE THREAD

**Issue by leipreachan** [freekode/tp2intervals#3]
Hi!

apparently there's an issue "yoga" should be considered as "Other" in terms of TP

```
2024-01-29T17:13:27.013Z ERROR 18 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request p[60/519]
g failed: feign.codec.DecodeException: Error while extracting response for type [java.util.List<org.freekode.tp2intervals.infrastructure.intervalsicu.workout.IntervalsEventDTO>] and content type [application
/json]] with root cause

com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `org.freekode.tp2intervals.infrastructure.intervalsicu.workout.IntervalsWorkoutType` from String "Yoga": not one of
 the values accepted for Enum class: [Other, WeightTraining, VirtualRide, Ride, Walk, Run, NOTE]
 at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1, column: 1148] (through reference chain: java.util.ArrayList[1]->org.freekode.tp2intervals.infrastructure.intervalsicu.worko
ut.IntervalsEventDTO["type"])
        at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67) ~[jackson-databind-2.15.3.jar!/:2.15.3]
        at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:2002) ~[jackson-databind-2.15.3.jar!/:2.15.3]
        at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:1230) ~[jackson-databind-2.15.3.jar!/:2.15.3]
        at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:415) ~[jackson-databind-2.15.3.jar!/:2.15.3]
        at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._fromString(EnumDeserializer.java:279) ~[jackson-databind-2.15.3.jar!/:2.15.3]
        at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:248) ~[jackson-databind-2.15.3.jar!/:2.15.3]
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:545) ~[jackson-databind-2.15.3.jar!/:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:570) ~[jackson-databind-2.15.3.jar!/:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439) ~[jackson-databind-2.15.3.jar!/:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1409) ~[jackson-databind-2.15.3.jar!/:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352) ~[jackson-databind-2.15.3.jar!/:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.15.3.jar!/:2.15.3]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359) ~[jackson-databind-2.15.3.jar!/:2.15.3]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244) ~[jackson-databind-2.15.3.jar!/:2.15.3]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28) ~[jackson-databind-2.15.3.jar!/:2.15.3]
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.15.3.jar!/:2.15.3]
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2105) ~[jackson-databind-2.15.3.jar!/:2.15.3]
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1481) ~[jackson-databind-2.15.3.jar!/:2.15.3]
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:395) ~[spring-web-6.1.1.jar!/:6.1.1]
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:354) ~[spring-web-6.1.1.jar!/:6.1.1]
        at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:103) ~[spring-web-6.1.1.jar!/:6.1.1]
        at org.springframework.cloud.openfeign.support.SpringDecoder.decode(SpringDecoder.java:70) ~[spring-cloud-openfeign-core-4.1.0.jar!/:4.1.0]
        at org.springframework.cloud.openfeign.support.ResponseEntityDecoder.decode(ResponseEntityDecoder.java:61) ~[spring-cloud-openfeign-core-4.1.0.jar!/:4.1.0]
        at feign.optionals.OptionalDecoder.decode(OptionalDecoder.java:36) ~[feign-core-13.1.jar!/:na]
        at feign.InvocationContext.decode(InvocationContext.java:114) ~[feign-core-13.1.jar!/:na]
        at feign.InvocationContext.proceed(InvocationContext.java:88) ~[feign-core-13.1.jar!/:na]
        at feign.ResponseHandler.handleResponse(ResponseHandler.java:63) ~[feign-core-13.1.jar!/:na]
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:114) ~[feign-core-13.1.jar!/:na]
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:70) ~[feign-core-13.1.jar!/:na]
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:99) ~[feign-core-13.1.jar!/:na]
        at org.springframework.cloud.openfeign.FeignCachingInvocationHandlerFactory$1.proceed(FeignCachingInvocationHandlerFactory.java:66) ~[spring-cloud-openfeign-core-4.1.0.jar!/:4.1.0]
        at org.springframework.cache.interceptor.CacheInterceptor.lambda$invoke$0(CacheInterceptor.java:64) ~[spring-context-6.1.1.jar!/:6.1.1]
        at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:392) ~[spring-context-6.1.1.jar!/:6.1.1]
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:377) ~[spring-context-6.1.1.jar!/:6.1.1]
        at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:74) ~[spring-context-6.1.1.jar!/:6.1.1]
        at org.springframework.cloud.openfeign.FeignCachingInvocationHandlerFactory.lambda$create$1(FeignCachingInvocationHandlerFactory.java:53) ~[spring-cloud-openfeign-core-4.1.0.jar!/:4.1.0]
        at jdk.proxy2/jdk.proxy2.$Proxy152.getEvents(Unknown Source) ~[na:na]
        at org.freekode.tp2intervals.infrastructure.intervalsicu.workout.IntervalsWorkoutRepository.getPlannedWorkouts(IntervalsWorkoutRepository.kt:45) ~[!/:0.0.4]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:352) ~[spring-aop-6.1.1.jar!/:6.1.1]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.1.1.jar!/:6.1.1]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.1.1.jar!/:6.1.1]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.1.jar!/:6.1.1]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-6.1.1.jar!/:6.1.1]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.1.1.jar!/:6.1.1]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.1.jar!/:6.1.1]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717) ~[spring-aop-6.1.1.jar!/:6.1.1]
        at org.freekode.tp2intervals.infrastructure.intervalsicu.workout.IntervalsWorkoutRepository$$SpringCGLIB$$0.getPlannedWorkouts(<generated>) ~[!/:0.0.4]
        at org.freekode.tp2intervals.app.WorkoutService.planTodayAndTomorrowWorkouts(WorkoutService.kt:34) ~[!/:0.0.4]
        at org.freekode.tp2intervals.rest.WorkoutController.planWorkout(WorkoutController.kt:16) ~[!/:0.0.4]
```

I may take a look at this myself but not till the end of the week

thanks!

**Comment by freekode** [comment]
Hi, thanks for the report.
I'm gonna take a look, probably will change the way how property mapped. All unknown will be mapped as others.

**Comment by freekode** [comment]
I made a fix, but not released it yet. If you want to try updated version you can download artifact here https://github.com/freekode/tp2intervals/actions/runs/7711698108/artifacts/1205554328
